# Generated by Django 4.2.30 on 2026-04-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_status_5b2843_idx',
            old_name='blog_post_status_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_slug_cdb902_idx',
            old_name='blog_post_slug_idx',
        ),
    ]
